# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f103d5e6d15e123d761f1fa2079d85fcc6643a1be2361b88a809e6a7f34830f69b988f886625645768c51d2f9950c61ba983addb1ea6fd2adc0290b8204c49

test:
  secret_key_base: 852658356563c683c4791313dbfffcee55d68fec2f9c75546b0247fe314cd4f66747883c68fa8bf50207fc874277cabe5a427b165b258a16f3fbf98f7009235c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
